create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table product (id bigint not null, name varchar(255) not null, image oid not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, time_for_cooking bigint, name varchar(255) not null, image oid not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table product (id bigint not null, name varchar(255) not null, image oid not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, time_for_cooking bigint, name varchar(255) not null, image oid not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint unique, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint unique, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product add constraint FKsouy49035ik9r5ojgslbv3i3u foreign key (image_id) references image;
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe add constraint FKky5g165dha9n8jdyx597kp9wa foreign key (image_id) references image;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint unique, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint unique, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product add constraint FKsouy49035ik9r5ojgslbv3i3u foreign key (image_id) references image;
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe add constraint FKky5g165dha9n8jdyx597kp9wa foreign key (image_id) references image;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint unique, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint unique, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product add constraint FKsouy49035ik9r5ojgslbv3i3u foreign key (image_id) references image;
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe add constraint FKky5g165dha9n8jdyx597kp9wa foreign key (image_id) references image;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint unique, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint unique, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product add constraint FKsouy49035ik9r5ojgslbv3i3u foreign key (image_id) references image;
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe add constraint FKky5g165dha9n8jdyx597kp9wa foreign key (image_id) references image;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint unique, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint unique, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product add constraint FKsouy49035ik9r5ojgslbv3i3u foreign key (image_id) references image;
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe add constraint FKky5g165dha9n8jdyx597kp9wa foreign key (image_id) references image;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint not null, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint not null, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint not null, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint not null, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint not null, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint not null, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint not null, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint not null, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint not null, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint not null, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
create sequence image_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence recipe_seq start with 1 increment by 50;
create sequence recipe_user_seq start with 1 increment by 50;
create table image (id bigint not null, path varchar(255) not null, primary key (id));
create table product (id bigint not null, image_id bigint not null, name varchar(255) not null, primary key (id));
create table product_recipes (product_id bigint not null, recipes_id bigint not null, primary key (product_id, recipes_id));
create table recipe (calorie bigint, id bigint not null, image_id bigint not null, time_for_cooking bigint, name varchar(255) not null, primary key (id));
create table recipe_ingredients (ingredients_id bigint not null, recipe_id bigint not null, primary key (ingredients_id, recipe_id));
create table recipe_likes (likes_user_id bigint not null, recipe_id bigint not null, primary key (likes_user_id, recipe_id));
create table recipe_user (user_id bigint not null, name varchar(255), password varchar(255), primary key (user_id));
create table recipe_user_favourites (favourites_id bigint not null, user_user_id bigint not null, primary key (favourites_id, user_user_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ADMIN','USER')));
alter table if exists product_recipes add constraint FKl1fanqw3vm30ku7scy7grcd4d foreign key (recipes_id) references recipe;
alter table if exists product_recipes add constraint FKnf2y9hi7ic31sbrj7hw0bx7oj foreign key (product_id) references product;
alter table if exists recipe_ingredients add constraint FK3r0jwvktfe1se5xp3s0g4irpt foreign key (ingredients_id) references product;
alter table if exists recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe;
alter table if exists recipe_likes add constraint FK7roy28co3a7x1h9g0nn63w9vf foreign key (likes_user_id) references recipe_user;
alter table if exists recipe_likes add constraint FKiu7ckx4lxgiegaku0nedh47pi foreign key (recipe_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKfqjbqqko969vnhdorbc9jqh15 foreign key (favourites_id) references recipe;
alter table if exists recipe_user_favourites add constraint FKaqoktcaaw883nr355de5k2i9n foreign key (user_user_id) references recipe_user;
alter table if exists user_role add constraint FKd4cssshrc5hqxq4x6vhb8ps2v foreign key (user_id) references recipe_user;
